{% set name = "pytest-azurepipelines" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-azurepipelines-{{ version }}.tar.gz
  sha256: 6f4246edbc13ef2a7f4584365289bc81a42618a00405582d0ce846e0a8ac60a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - pytest >=5.0.0
    - pytest-nunit >=0.6.0
    - python >=3.5

test:
  imports:
    - pytest_azurepipelines
  commands:
    - "py.test --traceconfig | grep pytest-azurepipelines-{{ version }}"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tonybaloney/pytest-azurepipelines
  summary: Formatting PyTest output for Azure Pipelines UI
  description: |
    Making Pytest easier to use with Microsoft Azure Pipelines. Just run pytest with
    this plugin and see your test results in the Azure Pipelines UI!
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/tonybaloney/pytest-azurepipelines

extra:
  recipe-maintainers:
    - leouieda
    - tonybaloney
